var userObj = {_x:28,_y:175,uID:classes.GlobalData.id,uName:classes.GlobalData.uname,tID:classes.GlobalData.attr.ti,tName:classes.GlobalData.attr.tn,uCred:classes.GlobalData.attr.sc};
this.attachMovie("userInfo","userInfo",1,userObj);
this.createEmptyMovieClip("car1",2);
car1.racerNumSeq = _parent.myRacerNum;
classes.Drawing.carView(car1,new XML(classes.GlobalData.getSelectedCarXML().toString()),62);
car1._x = 396;
car1._y = 129;
var clrMtx = new Array();
clrMtx = clrMtx.concat([0.5,0,0,0,0]);
clrMtx = clrMtx.concat([0,0.5,0,0,0]);
clrMtx = clrMtx.concat([0,0,0.5,0,0]);
clrMtx = clrMtx.concat([0,0,0,1,0]);
var fltr = new flash.filters.ColorMatrixFilter(clrMtx);
car1.filters = new Array(fltr);
