stop();
_root.dialogCreateAccount = this;
var guid;
var infoXML;
var selCarID;
var selCarIdx = 0;
var selColor;
var selWheelIdx = 0;
var selWheelID;
var selWheelPartID;
var selWheelSize;
var selTireSize;
var selRideHeight;
var carsNode;
var wheelsNode;
var isBack;
var wheelsArr;
var username;
txtU = "";
txtPW = "";
txtCPW = "";
txtE = "";
txtZ = "";
txtY = "";
txtCode = "";
_root.openFile("cache/cd.txt");
