_global.releaseNumber = "0.10.03";
var splashPre = "PUBLIC BETA ";
var splashText = splashPre + _global.releaseNumber;
trace("here we go");
getURL("FSCommand:" add "fullscreen",true,"GET");
getURL("FSCommand:" add "allowscale",false,"GET");
_focusrect = false;
this.createEmptyMovieClip("sx",this.getNextHighestDepth());
sx.createEmptyMovieClip("boo",sx.getNextHighestDepth());
sx.createEmptyMovieClip("cheer",sx.getNextHighestDepth());
sx.boo.snd = new Sound(sx.boo);
sx.boo.snd.attachSound("boo");
sx.cheer.snd = new Sound(sx.cheer);
sx.cheer.snd.attachSound("cheer");
