mb.prepPanelRemove();
menuMC.removeMovieClip();
var selectedCarXML = new XML(classes.GlobalData.getSelectedCarXML().toString());
var cs = new classes.CarSpecs();
cs.applyCarXML(selectedCarXML);
var carID = selectedCarXML.firstChild.attributes.ci;
image_mc.removeMovieClip();
this.createEmptyMovieClip("image_mc",this.getNextHighestDepth());
image_mc._x = 184;
image_mc._y = 92;
classes.Drawing.carView(image_mc,selectedCarXML,100,"back");
